# Generated by Django 5.2.1 on 2026-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TumaGo_Server', '0003_customuser_identity_customuser_license_picture_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='driver_available',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='driver_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('driver', 'Driver')], db_index=True, default='user', max_length=10),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'driver_online', 'driver_available'], name='idx_driver_matching'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'date'], name='idx_delivery_driver_date'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['client', 'date'], name='idx_delivery_client_date'),
        ),
    ]
